CREATE TABLE pups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    breed TEXT NOT NULL,
    mix BOOLEAN NOT NULL,
    age TEXT NOT NULL,
    size VARCHAR(1) NOT NULL,
    nervous BOOLEAN NOT NULL,
    rambunctious BOOLEAN NOT NULL,
    gentle BOOLEAN NOT NULL,
    wrestling BOOLEAN NOT NULL,
    walks BOOLEAN NOT NULL,
    parks BOOLEAN NOT NULL,
    foodobsessed BOOLEAN NOT NULL,
    ballobsessed BOOLEAN NOT NULL,
    description TEXT, 
    owner INTEGER REFERENCES pupdate_users(id) ON DELETE CASCADE NOT NULL,
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL
);

