CREATE TABLE pupdates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL,
    starttime TIME NOT NULL,
    endtime TIME NOT NULL,
    location TEXT NOT NULL,
    organizer INTEGER REFERENCES pupdate_users(id),
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);